use std::{env::var, path::Path, process::Command};

use anyhow::{Result, bail};
use parking_lot::Mutex;

fn no_display() -> bool {
    let is_ci = var("GITHUB_ACTIONS").is_ok() || var("CI").is_ok();

    let is_headless_linux =
        cfg!(target_os = "linux") && var("DISPLAY").is_err() && var("WAYLAND_DISPLAY").is_err();

    is_ci || is_headless_linux
}

/// Backs the `#[test]` generated by `#[view_test]`: runs the test in the app
/// with a live window, or headless when there is no display.
pub fn run_test_app(manifest_dir: &str, test_name: &str) -> Result<()> {
    // `cargo test` runs tests in parallel - run one app at a time.
    static LOCK: Mutex<()> = Mutex::new(());
    let _guard = LOCK.lock();

    let target_dir = Path::new(manifest_dir).join("../target/ui_tests");

    let mut command = Command::new("cargo");

    command.args(["run", "-p", "ui-test", "--target-dir"]).arg(target_dir).args([
        "--",
        "--test-name",
        test_name,
        "--stop-on-failure",
    ]);

    if no_display() {
        command.arg("--headless");
    }

    let status = command.status()?;

    if !status.success() {
        bail!("UI test {test_name} failed: {status}");
    }

    Ok(())
}
